name: CROUS Scraper

on:
  schedule:
<<<<<<< HEAD
    - cron: '*/11 6-16 * * *' # Runs every 11 minutes
=======
    - cron: '*/9 * * * *' # Runs every 10 minutes
>>>>>>> 5fea789f3d7d7a9629a3076ba25dc5661afd3df1
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scraper.py
